### ISSUE TITLE
windows - port libsasl2 to windows (was: smtp doesn’t  work)

### ISSUE THREAD

**Issue by naderi4** [dinhvh/libetpan#177]
![capture](https://cloud.githubusercontent.com/assets/10121766/5348211/be0570dc-7f25-11e4-9bfe-27f8eaae4388.PNG)
i test libetpan pop3 , imap and smtp
but smtp dosent work 

smtpsend.c sample
mailsmtp.c line: 1263

r = sasl_client_start(session->smtp_sasl.sasl_conn,
      auth_type, NULL, &sasl_out, &sasl_out_len, &mechusing);
  if ((r != SASL_CONTINUE) && (r != SASL_OK)) {
    res = MAILSMTP_ERROR_AUTH_LOGIN;
    goto free_sasl_conn;
  }

return -4 

windows 7 + visual studio 2013 
my setting is
-f "XXXXXX@gmail.com" -u "XXXXXX@gmail.com" -v "XXXXXX" -s "smtp.gmail.com" -p 587 -S "XXXXXX@gmail.com"

thanks for your help

**Comment by cuisinart** [comment]
Hi Naderi4, I am having exactly this problem.  Can you make your build/port of libsasl2 available?

**Comment by naderi4** [comment]
yes i do

**Comment by cuisinart** [comment]
Thank you. Can you post a link? Are you building it with Visual Studio or GCC?

**Comment by dinhviethoa** [comment]
Yep. I'll be interested in your changes to libsasl to update:

- https://github.com/dinhviethoa/cyrus-sasl/tree/master/build-windows
- and to update the binaries at this location: http://d.etpan.org/mailcore2-deps/cyrus-sasl-win32/

Thanks!

**Comment by cuisinart** [comment]
Ok, I have this working now and can get together a pull request for libsasl2 in a while.  libsasl has a bit of an odd plugin scheme with external dll plugins, but it's possible to build the plugins into the libsasl2 dll without making them external .dlls. This change should reduce potential problems with the most used authentication methods

**Comment by dinhviethoa** [comment]
Sounds great! Go ahead and send the pull request when you're ready!

**Comment by cuisinart** [comment]
Done. This resolves #1116. It's nice to have fully working IMAP, IDLE, and SMTP sending via gmail now with mailcore in Windows.  Thank you for your efforts with supporting the MSVC 2013 IDE. It makes this all so much easier.
