### ISSUE TITLE
potential memory leak in use of realloc

### ISSUE THREAD

**Issue by ptroja** [dinhvh/libetpan#261]
Detected with cppcheck:

[src/low-level/mime/mailmime_decode.c:675]: (error) Common realloc mistake: 'body' nulled but not freed upon failure

For me it seems unlikely to happen, but still should be avoided.

**Comment by dinhviethoa** [comment]
Could you point out to the updated location in the code?
Thanks!

**Comment by ptroja** [comment]
[src/low-level/mime/mailmime_decode.c:501]: (error) Common realloc mistake: 'body' nulled but not freed upon failure

I forgot to mention that this was detected by cppcheck
