### ISSUE TITLE
Export micro version

### ISSUE THREAD

**Issue by mones** [dinhvh/libetpan#276]
Hi Hoa!

Just noticed that I forgot to add micro version to the set of exported version macros/functions in the fix for #256.
The attached patch solves this problem (has an additional txt extension because of github's...).

Thanks!

[0001-Export-also-micro-version.patch.txt](https://github.com/dinhviethoa/libetpan/files/1116988/0001-Export-also-micro-version.patch.txt)

**Comment by mones** [comment]
Hi! Has passed some time since this, so just wondering... is there any problem with this patch?

**Comment by dinhviethoa** [comment]
Could you send a pull request instead? It would help integrate it faster ;)
Thanks!

**Comment by mones** [comment]
In case you didn't notice it yet I've sent it as PR https://github.com/dinhvh/libetpan/pull/389 ;-)

**Comment by dinhvh** [comment]
Sorry about the long delay!

**Comment by mones** [comment]
No problem! Thanks! 😸
