### ISSUE TITLE
Build failed with Xcode 12

### ISSUE THREAD

**Issue by Vincentzzg** [dinhvh/libetpan#404]
<img width="1527" alt="截屏2021-04-26 下午8 00 16" src="https://user-images.githubusercontent.com/10241716/116079364-4c619400-a6ca-11eb-8fa8-efed89d4a9c5.png">

**Comment by haithngn** [comment]
Which kind of Mac machine do you running on? Intel chip or ARM chip?

**Comment by Vincentzzg** [comment]
Intel chip.

<img width="546" alt="截屏2021-04-27 上午9 16 22" src="https://user-images.githubusercontent.com/10241716/116170368-3dfe9100-a739-11eb-9eab-16fb167d7cea.png">

**Comment by haithngn** [comment]
<img width="1440" alt="Screen Shot 2021-04-27 at 09 21 34" src="https://user-images.githubusercontent.com/22902671/116175229-1e1b9d00-a73a-11eb-8fd1-e0a8aa4e3475.png">
I have no idea about your case, I think that is not related to libetpan you should Google it.
anw, can you try on another machine?

**Comment by Vincentzzg** [comment]
The cause of the problem is that the architecture of the executable file is arm_v7, but the computer is an Intel chip.

<img width="625" alt="截屏2021-04-27 上午11 23 02" src="https://user-images.githubusercontent.com/10241716/116180091-f123b600-a74a-11eb-8b26-b4174e930893.png">

<img width="372" alt="截屏2021-04-27 上午11 24 17" src="https://user-images.githubusercontent.com/10241716/116180287-38aa4200-a74b-11eb-96e4-b4154a7c8fc5.png">

**Comment by Vincentzzg** [comment]
I don't know where the program went wrong.

The earliest error is here：
<img width="1134" alt="截屏2021-04-27 下午3 29 32" src="https://user-images.githubusercontent.com/10241716/116202702-761fc700-a76d-11eb-9d0a-48344bb70fd4.png">


Corresponds to line 159 of the code in the prepare-cyrus-sasl.sh file.
<img width="960" alt="截屏2021-04-27 下午3 33 21" src="https://user-images.githubusercontent.com/10241716/116203308-21c91700-a76e-11eb-8936-cb3d1b9a846c.png">

Then the code came to the exit.

It should be the failure here that led to the ultimate failure.

**Comment by KennethFra** [comment]
Same issue here.  Is there a workaround?

**Comment by Vincentzzg** [comment]
@KennethFra @haithngn 
The solution is to modify version=2.1.26 in the prepare-cyrus-sasl.sh file to version=2.1.27.
