### ISSUE TITLE
Build fails macOS 12.2.1

### ISSUE THREAD

**Issue by KodaKoder** [dinhvh/libetpan#414]
Building libetpan iOS on simulator/device fails 
Xcode 13.3 (13E113)
macOS 12.2.1 (21D62) 
iMac x86

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in include
gcc -DHAVE_CONFIG_H -I. -I..   -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -DOBSOLETE_CRAM_ATTR=1  -Wall -W -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -Os -fembed-bitcode -miphoneos-version-min=7.0 -MT makemd5.o -MD -MP -MF .deps/makemd5.Tpo -c -o makemd5.o makemd5.c
mv -f .deps/makemd5.Tpo .deps/makemd5.Po
/bin/sh ../libtool   --mode=link gcc  -Wall -W -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -Os -fembed-bitcode -miphoneos-version-min=7.0   -o makemd5 makemd5.o  -lresolv  
mkdir .libs
gcc -Wall -W -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -Os -fembed-bitcode -miphoneos-version-min=7.0 -o makemd5 makemd5.o -lresolv
rm -f md5global.h
./makemd5 md5global.h
make[2]: ./makemd5: Bad CPU type in executable
make[2]: *** [md5global.h] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by dinhvh** [comment]
Fixed with https://github.com/dinhvh/libetpan/commit/0e81583a403b7e3e2cc6fede3b5c9ba1d7693e22
