### ISSUE TITLE
[BUG] Hang / performance problems with commit

### ISSUE THREAD

**Issue by guidedways** [dinhvh/libetpan#421]
I can verify that this commit creates serious performance issues - parsing 'never' ends for certain emails: fc3c6a6418f0ebf2ca70887398086bbf3a0bdee8

We had to revert to the version before this to get it to work properly.

**Comment by 77tb** [comment]
+1

**Comment by dinhvh** [comment]
It's been reverted now. Thank you for raising the issue!
